//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public Nullable<int> category { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
